name: Application CI
on: [push, pull_request]
jobs:
  pipeline:
    name: serviceAwas pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Package application
        run: npm run java:jar:prod
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Build and publish docker image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        run: |
          ./mvnw -ntp jib:build -Djib.to.image=darizkipratama/sipdasrh-awas:latest -Djib.to.auth.username="darizkipratama" -Djib.to.auth.password="dckr_pat_I9gAXAaH23uDAbapOVEWkIv4Xks" -Pprod
